/**
 * planetary.ts — #61 Infinite Coordination + #62 Planetary Intelligence. Honest positioning: these are
 * SCALE restatements of engines ORB already has — #61 is #39 Universal Coordination pushed to "unlimited
 * agents", #62 is #38 Civilization OS pushed to "the whole planet as one mind". To avoid firing
 * redundant directives on the same questions, both are scoped tightly to phrasings that explicitly
 * invoke planetary/global/unlimited scale, and each adds only the altitude #39/#38 don't already carry.
 *
 * Both are directive engines. Honest scope (unchanged and important): ORB is a per-user system. It
 * reasons ABOUT planetary coordination and global systems; it is not a planetary control plane and does
 * not sense or act at global scale. The human stays sovereign. No store.
 */

// #61 — coordination at unlimited scale (the scale extension of #39).
export const INFCOORD_QUERY = /\b(coordinate (?:at|across) (?:planetary|global|massive|unlimited|civilization) scale|(?:planetary|global|civilization)[- ]?(?:wide|scale) coordination|synchroni[sz]e (?:intelligence|systems|agents|everyone) (?:at scale|globally|across)|align (?:millions|billions|countless|unlimited) (?:agents|people|systems|minds)|coordinate (?:humans? and ai|ai agents and|across (?:nations|civilizations))|orchestrate (?:at )?(?:massive|global|planetary) scale|how (?:do|can) (?:millions|billions|countless) (?:coordinate|align|act together))\b/i;
export const INFCOORD_DIRECTIVE = ' Reason about coordination at large scale: align goals → strategies → actions → outcomes across many independent agents, and get the right information to the right agent at the right time. Focus on the leverage that scales — aligned incentives (find what benefits everyone), clean information flow, and clear ownership — and the failure modes that scale worse (friction, redundancy, conflict, bottlenecks). Use distributed intelligence: no single node solves everything; the network does. Stay grounded in what this person can actually influence, human sovereign over any large call.';

// #62 — the planet as one sensing/learning/adapting system (the scale extension of #38).
export const PLANETARY_QUERY = /\b(planetary (?:intelligence|scale|nervous system|awareness|system)|the (?:whole )?planet (?:as|thinking|functioning)|global (?:systems?|coordination|challenges?|risks?|knowledge)|humanity (?:thinking|acting|learning) (?:as one|together at scale)|civili[sz]ation as (?:a|one) (?:system|intelligence|mind)|species[- ]level|earth (?:system|as a)|cascade failures?|systemic global|at the scale of (?:the planet|a (?:planet|civilization))|global feedback)\b/i;
export const PLANETARY_DIRECTIVE = ' Hold the planetary-systems view: treat humanity, institutions, technology, and the environment as one increasingly interconnected system where what affects one region eventually affects others. Trace the global feedback loops (action → outcome → feedback → adaptation), watch for systemic risk and cascade failure across the connections, and look for leverage where a change compounds across the whole. Many of the hardest problems (climate, pandemics, energy, security) are global and solved by no one alone — so weigh cooperation and resilience (adaptability, redundancy, knowledge-sharing). Keep it grounded in what this person can actually move, human sovereign over any planetary-scale call.';

// #63 — species advancement (the scale extension of #56 Human Potential + #55, at the level of humanity itself).
export const SPECIES_QUERY = /\b(species[- ]?(?:advancement|level|wide)|humanity('?s)? (?:potential|advancement|future|flourishing|progress|evolution)|advance (?:humanity|the species|the human race)|human (?:progress|advancement) at scale|leave humanity (?:better|stronger)|future of the (?:human )?species|how (?:do|should) (?:we|humanity) (?:improve|advance|evolve) (?:as a species|humanity)|the next stage of human|long[- ]?term (?:future|survival) of humanity|better version of (?:humanity|the species)|human (?:capability|flourishing) (?:at scale|for all))\b/i;
export const SPECIES_DIRECTIVE = ' Reason at the level of humanity, not just the individual: assume the species is not finished evolving and ask what most expands its collective capability — health, knowledge, creativity, wisdom, cooperation, adaptability — and leaves humanity stronger than we found it. Favor the leverage that scales to billions (education, health, science, governance, cooperation), and weigh outcomes on a long horizon (decades to centuries) over quarterly ones. Adaptability is survival: prize the ability to learn and respond faster than challenges emerge. Keep it grounded in what this person can actually influence and contribute, human sovereign over any species-scale call.';

// #64 — existential / catastrophic risk + resilience (survive before you flourish). Adjacent to #34
// Antifragility and #19 Stewardship, scoped to irreversible, large-scale threats and the resilience to them.
export const EXISTENTIAL_QUERY = /\b(existential (?:risk|threat)|catastrophic (?:risk|failure|threat)|irreversible (?:harm|damage|collapse|loss)|civili[sz]ation(?:al)? (?:collapse|risk|survival)|extinction|cascade (?:failure|risk)|systemic (?:risk|collapse|fragility)|what could (?:permanently|catastrophically|irreversibly) (?:go wrong|harm|destroy|end)|threats? to (?:humanity|civili[sz]ation|our future|future generations?)|single point of (?:catastrophic )?failure|tail risk|black swan|how (?:do|can) (?:we|humanity) survive|protect (?:humanity|civili[sz]ation|the future)|long[- ]?term survival)\b/i;
export const EXISTENTIAL_DIRECTIVE = ' Before flourishing, survival: weigh whether anything here carries catastrophic or irreversible downside, even at low probability — the kind that permanently forecloses future potential. Score threats by impact × scale × irreversibility, not just likelihood, and treat a small irreversible risk as more serious than a large recoverable one. Look for fragile systems, missing redundancy, and where one failure could cascade. Because not every threat is predictable, favor resilience over forecasting — adaptability, redundancy, recovery capability, preserved knowledge. Name the most serious irreversible risk and the cheapest safeguard or margin that meaningfully reduces it, human sovereign over the call.';

// #65 — intergenerational stewardship (adjacent to #18 long view, #19 stewardship, #41 preservation;
// scoped to the duty-to-future-generations / what-we-pass-forward facet).
export const INTERGEN_QUERY = /\b(future generations?|generations? (?:to come|from now|yet to come)|(?:people|those) (?:not yet|who aren'?t yet) born|seven generations?|intergenerational|what (?:do |are )?we (?:owe|passing) (?:to )?(?:the future|future generations|our (?:kids|children|grandchildren))|leave (?:the world|things|it) better|(?:for|to) our (?:grandchildren|descendants|kids'? kids)|long[- ]?term inheritance|what (?:are )?we (?:leaving|passing) (?:forward|behind|on)|borrow(?:ed|ing)? (?:it )?from (?:the|our) (?:future|children)|stewardship (?:across|over) time|hundred years? from now|leave (?:the future|things|it|the world) (?:stronger|better) than (?:we|i) (?:found|inherited)|leave the future (?:stronger|better)|temporary custodian|custodians? of (?:the future|what)|stewards? of the future|protect and (?:improve|advance|pass) (?:what|everything|value)|pass (?:it|value|this) forward|protect.{0,20}?for (?:the |future )?generations?)\b/i;
export const INTERGEN_DIRECTIVE = ' Steward across time: weigh this not only for today but for people not yet born, as if the future were borrowed from them rather than owned. Stretch the horizon — immediate → decade → generational → civilizational — and ask what this passes forward: opportunity and knowledge, or debt and risk. Favor choices that compound value across generations and that preserve what\'s hard to rebuild (knowledge, institutions, trust, natural and built capital), while still meeting real present needs — balance, not sacrifice of either. End on the choice future generations would thank them for, and the one thing most worth preserving or not foreclosing now.';
